export const channels = {
  pickV1Asset: "v1:pick-asset",
  runV1Job: "v1:run",
  listV1Jobs: "v1:list",
  compileExplorerProgram: "explorer:compile-program",
  checkForUpdate: "app:check-for-update",
  getOpenCodeInfo: "opencode:get-info",
  openCodeStartupProgress: "opencode:startup-progress",
  getInstructionFiles: "opencode:get-instruction-files",
  getVersion: "app:get-version",
  installUpdate: "app:install-update",
  invokeExplorerProgram: "explorer:invoke-program",
  loadConfig: "config:load",
  openUrl: "app:open-url",
  patchConfig: "config:patch",
  relaunch: "app:relaunch",
  discoverStudioTargets: "studio-target:discover",
  installStudioTargetPrograms: "studio-target:install-programs",
  selectStudioTarget: "studio-target:select",
} as const;
